name: Automerge

on:
  push:
    branches:
    - master

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "release"
        github_token: ${{ secrets.GITHUB_TOKEN }}
